import type { BuiltinEntry } from './types';

const shaderLabStateDetail = 'ShaderLab render state';
const shaderLabValueDetail = 'ShaderLab state value';

export const BUILTIN_ENTRIES = [
  {
    name: 'float2',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Two-component 32-bit floating point vector.',
  },
  {
    name: 'float3',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Three-component 32-bit floating point vector.',
  },
  {
    name: 'float4',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Four-component 32-bit floating point vector.',
  },
  {
    name: 'half',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL scalar type',
    documentation: '16-bit floating point scalar used in shader code.',
  },
  {
    name: 'half2',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Two-component half precision vector.',
  },
  {
    name: 'half3',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Three-component half precision vector.',
  },
  {
    name: 'half4',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Four-component half precision vector.',
  },
  {
    name: 'normalize',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Returns x scaled to unit length.',
  },
  {
    name: 'dot',
    kind: 'function',
    category: 'hlsl',
    returnType: 'scalar',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the dot product of x and y.',
  },
  {
    name: 'cross',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the cross product of two 3D vectors.',
  },
  {
    name: 'lerp',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
      { type: 'T', name: 's' },
    ],
    documentation: 'Linearly interpolates between x and y by s.',
  },
  {
    name: 'saturate',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Clamps x to the 0 to 1 range.',
  },
  {
    name: 'mul',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Performs matrix and vector multiplication.',
  },
  {
    name: 'clamp',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'minValue' },
      { type: 'T', name: 'maxValue' },
    ],
    documentation: 'Clamps x to the supplied range.',
  },
  {
    name: 'min',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the lesser of x and y.',
  },
  {
    name: 'max',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the greater of x and y.',
  },
  {
    name: 'pow',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns x raised to the power y.',
  },
  {
    name: 'sin',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Returns the sine of x.',
  },
  {
    name: 'cos',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Returns the cosine of x.',
  },
  {
    name: 'tex2D',
    kind: 'function',
    category: 'hlsl',
    returnType: 'float4',
    parameters: [
      { type: 'sampler2D', name: 'sampler' },
      { type: 'float2', name: 'uv' },
    ],
    documentation: 'Samples a texture using a sampler and UV coordinate.',
  },
  // === HLSL math intrinsics ===
  { name: 'abs', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the absolute value of x.' },
  { name: 'sign', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns -1, 0, or 1 indicating the sign of x.' },
  { name: 'floor', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the largest integer not greater than x.' },
  { name: 'ceil', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the smallest integer not less than x.' },
  { name: 'round', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Rounds x to the nearest integer.' },
  { name: 'frac', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the fractional part of x.' },
  { name: 'fmod', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }, { type: 'T', name: 'y' }], documentation: 'Returns the floating-point remainder of x / y.' },
  { name: 'step', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'edge' }, { type: 'T', name: 'x' }], documentation: 'Returns 1 if x >= edge, otherwise 0.' },
  { name: 'smoothstep', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'edge0' }, { type: 'T', name: 'edge1' }, { type: 'T', name: 'x' }], documentation: 'Returns a smooth Hermite interpolation between 0 and 1.' },
  { name: 'sqrt', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the square root of x.' },
  { name: 'rsqrt', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the reciprocal square root of x.' },
  { name: 'exp', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns e raised to the power x.' },
  { name: 'exp2', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns 2 raised to the power x.' },
  { name: 'log', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the natural logarithm of x.' },
  { name: 'log2', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the base-2 logarithm of x.' },
  { name: 'mad', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'a' }, { type: 'T', name: 'b' }, { type: 'T', name: 'c' }], documentation: 'Returns a * b + c using a fused multiply-add when available.' },
  { name: 'rcp', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the approximate reciprocal of x.' },
  { name: 'tan', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the tangent of x.' },
  { name: 'asin', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the arcsine of x.' },
  { name: 'acos', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the arccosine of x.' },
  { name: 'atan', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the arctangent of x.' },
  { name: 'atan2', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'y' }, { type: 'T', name: 'x' }], documentation: 'Returns the arctangent of y / x using the signs to choose the quadrant.' },
  { name: 'radians', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'degrees' }], documentation: 'Converts degrees to radians.' },
  { name: 'degrees', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'radians' }], documentation: 'Converts radians to degrees.' },
  // === HLSL geometry helpers ===
  { name: 'length', kind: 'function', category: 'hlsl', returnType: 'scalar', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the length of vector x.' },
  { name: 'distance', kind: 'function', category: 'hlsl', returnType: 'scalar', parameters: [{ type: 'T', name: 'x' }, { type: 'T', name: 'y' }], documentation: 'Returns the distance between vectors x and y.' },
  { name: 'reflect', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'i' }, { type: 'T', name: 'n' }], documentation: 'Returns i reflected across normal n.' },
  { name: 'refract', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'i' }, { type: 'T', name: 'n' }, { type: 'scalar', name: 'eta' }], documentation: 'Returns i refracted through the surface defined by normal n and ratio eta.' },
  { name: 'transpose', kind: 'function', category: 'hlsl', returnType: 'matrix', parameters: [{ type: 'matrix', name: 'm' }], documentation: 'Returns the transpose of matrix m.' },
  { name: 'determinant', kind: 'function', category: 'hlsl', returnType: 'scalar', parameters: [{ type: 'matrix', name: 'm' }], documentation: 'Returns the determinant of matrix m.' },
  { name: 'lit', kind: 'function', category: 'hlsl', returnType: 'float4', parameters: [{ type: 'scalar', name: 'nDotL' }, { type: 'scalar', name: 'nDotH' }, { type: 'scalar', name: 'm' }], documentation: 'Returns a lighting coefficient vector (ambient, diffuse, specular, 1).' },
  // === HLSL derivatives and per-pixel helpers ===
  { name: 'ddx', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the partial derivative of x with respect to the screen-space x coordinate.' },
  { name: 'ddy', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns the partial derivative of x with respect to the screen-space y coordinate.' },
  { name: 'ddx_fine', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Higher-precision variant of ddx.' },
  { name: 'ddy_fine', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Higher-precision variant of ddy.' },
  { name: 'fwidth', kind: 'function', category: 'hlsl', returnType: 'T', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns |ddx(x)| + |ddy(x)|.' },
  { name: 'any', kind: 'function', category: 'hlsl', returnType: 'bool', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns true if any component of x is non-zero.' },
  { name: 'all', kind: 'function', category: 'hlsl', returnType: 'bool', parameters: [{ type: 'T', name: 'x' }], documentation: 'Returns true if all components of x are non-zero.' },
  { name: 'clip', kind: 'function', category: 'hlsl', returnType: 'void', parameters: [{ type: 'T', name: 'x' }], documentation: 'Discards the current pixel if any component of x is negative.' },
  { name: 'firstbithigh', kind: 'function', category: 'hlsl', returnType: 'uint', parameters: [{ type: 'uint', name: 'x' }], documentation: 'Returns the position of the highest set bit in x.' },
  { name: 'countbits', kind: 'function', category: 'hlsl', returnType: 'uint', parameters: [{ type: 'uint', name: 'x' }], documentation: 'Returns the number of bits set in x.' },
  { name: 'discard', kind: 'keyword', category: 'hlsl', detail: 'HLSL statement', documentation: 'Discards the current pixel.' },
  // === HLSL scalar and vector types ===
  { name: 'int', kind: 'type', category: 'hlsl', detail: 'HLSL scalar type', documentation: 'Signed 32-bit integer scalar.' },
  { name: 'int2', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Two-component signed integer vector.' },
  { name: 'int3', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Three-component signed integer vector.' },
  { name: 'int4', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Four-component signed integer vector.' },
  { name: 'uint', kind: 'type', category: 'hlsl', detail: 'HLSL scalar type', documentation: 'Unsigned 32-bit integer scalar.' },
  { name: 'uint2', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Two-component unsigned integer vector.' },
  { name: 'uint3', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Three-component unsigned integer vector.' },
  { name: 'uint4', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Four-component unsigned integer vector.' },
  { name: 'bool', kind: 'type', category: 'hlsl', detail: 'HLSL scalar type', documentation: 'Boolean scalar.' },
  { name: 'bool2', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Two-component boolean vector.' },
  { name: 'bool3', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Three-component boolean vector.' },
  { name: 'bool4', kind: 'type', category: 'hlsl', detail: 'HLSL vector type', documentation: 'Four-component boolean vector.' },
  // === HLSL matrix types ===
  { name: 'float2x2', kind: 'type', category: 'hlsl', detail: 'HLSL matrix type', documentation: '2x2 32-bit floating point matrix.' },
  { name: 'float3x3', kind: 'type', category: 'hlsl', detail: 'HLSL matrix type', documentation: '3x3 32-bit floating point matrix.' },
  { name: 'float4x4', kind: 'type', category: 'hlsl', detail: 'HLSL matrix type', documentation: '4x4 32-bit floating point matrix.' },
  { name: 'half2x2', kind: 'type', category: 'hlsl', detail: 'HLSL matrix type', documentation: '2x2 half precision matrix.' },
  { name: 'half3x3', kind: 'type', category: 'hlsl', detail: 'HLSL matrix type', documentation: '3x3 half precision matrix.' },
  { name: 'half4x4', kind: 'type', category: 'hlsl', detail: 'HLSL matrix type', documentation: '4x4 half precision matrix.' },
  // === HLSL resource types ===
  { name: 'Texture2D', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Two-dimensional texture resource.' },
  { name: 'Texture2DArray', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Array of two-dimensional textures.' },
  { name: 'Texture3D', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Three-dimensional texture resource.' },
  { name: 'TextureCube', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Cube map texture resource.' },
  { name: 'TextureCubeArray', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Array of cube map texture resources.' },
  { name: 'SamplerState', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Standalone sampler state object.' },
  { name: 'SamplerComparisonState', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Sampler state object for comparison sampling.' },
  { name: 'RWTexture2D', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Read-write 2D texture resource for compute shaders.' },
  { name: 'StructuredBuffer', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Read-only buffer of user-defined structs.' },
  { name: 'RWStructuredBuffer', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Read-write buffer of user-defined structs.' },
  { name: 'ByteAddressBuffer', kind: 'type', category: 'hlsl', detail: 'HLSL resource type', documentation: 'Byte-addressable read-only buffer.' },
  {
    name: 'UnityObjectToClipPos',
    kind: 'function',
    category: 'unitycg',
    returnType: 'float4',
    parameters: [{ type: 'float3', name: 'pos' }],
    documentation: 'Transforms object-space position to homogeneous clip space.',
  },
  {
    name: 'TRANSFORM_TEX',
    kind: 'macro',
    category: 'unitycg',
    detail: 'UnityCG texture transform macro',
    documentation: 'Applies Unity texture scale and offset to a UV coordinate.',
  },
  {
    name: 'SAMPLE_TEXTURE2D',
    kind: 'macro',
    category: 'urp',
    detail: 'URP texture sampling macro',
    documentation: 'Samples a Texture2D with an explicit sampler and UV coordinate.',
  },
  {
    name: 'TEXTURE2D',
    kind: 'macro',
    category: 'urp',
    detail: 'URP texture declaration macro',
    documentation: 'Declares a Texture2D resource.',
  },
  {
    name: 'SAMPLER',
    kind: 'macro',
    category: 'urp',
    detail: 'URP sampler declaration macro',
    documentation: 'Declares a sampler state.',
  },
  // === URP/SRP Core texture sampling and declaration macros ===
  { name: 'SAMPLE_TEXTURE2D_LOD', kind: 'macro', category: 'urp', detail: 'URP texture sampling macro', documentation: 'Samples a Texture2D at an explicit mip level.' },
  { name: 'SAMPLE_TEXTURE2D_GRAD', kind: 'macro', category: 'urp', detail: 'URP texture sampling macro', documentation: 'Samples a Texture2D using explicit derivatives.' },
  { name: 'SAMPLE_TEXTURE2D_ARRAY', kind: 'macro', category: 'urp', detail: 'URP texture sampling macro', documentation: 'Samples a Texture2DArray slice.' },
  { name: 'SAMPLE_TEXTURECUBE', kind: 'macro', category: 'urp', detail: 'URP texture sampling macro', documentation: 'Samples a TextureCube using a direction vector.' },
  { name: 'TEXTURECUBE', kind: 'macro', category: 'urp', detail: 'URP texture declaration macro', documentation: 'Declares a TextureCube resource.' },
  { name: 'TEXTURE2D_ARRAY', kind: 'macro', category: 'urp', detail: 'URP texture declaration macro', documentation: 'Declares a Texture2DArray resource.' },
  { name: 'TEXTURE2D_PARAM', kind: 'macro', category: 'urp', detail: 'URP texture parameter macro', documentation: 'Declares a Texture2D function parameter together with its sampler.' },
  { name: 'TEXTURE2D_ARGS', kind: 'macro', category: 'urp', detail: 'URP texture argument macro', documentation: 'Forwards a Texture2D and its sampler as function arguments.' },
  // === URP/SRP Core transformation helpers ===
  { name: 'TransformObjectToWorld', kind: 'function', category: 'urp', returnType: 'float3', parameters: [{ type: 'float3', name: 'positionOS' }], documentation: 'Transforms an object-space position to world space.' },
  { name: 'TransformObjectToHClip', kind: 'function', category: 'urp', returnType: 'float4', parameters: [{ type: 'float3', name: 'positionOS' }], documentation: 'Transforms an object-space position to homogeneous clip space.' },
  { name: 'TransformWorldToHClip', kind: 'function', category: 'urp', returnType: 'float4', parameters: [{ type: 'float3', name: 'positionWS' }], documentation: 'Transforms a world-space position to homogeneous clip space.' },
  { name: 'TransformObjectToWorldNormal', kind: 'function', category: 'urp', returnType: 'float3', parameters: [{ type: 'float3', name: 'normalOS' }], documentation: 'Transforms an object-space normal to world space.' },
  { name: 'TransformWorldToView', kind: 'function', category: 'urp', returnType: 'float3', parameters: [{ type: 'float3', name: 'positionWS' }], documentation: 'Transforms a world-space position to view space.' },
  { name: 'GetWorldSpaceViewDir', kind: 'function', category: 'urp', returnType: 'float3', parameters: [{ type: 'float3', name: 'positionWS' }], documentation: 'Returns the unnormalized world-space view direction from a position.' },
  { name: 'GetWorldSpaceNormalizeViewDir', kind: 'function', category: 'urp', returnType: 'float3', parameters: [{ type: 'float3', name: 'positionWS' }], documentation: 'Returns the normalized world-space view direction from a position.' },
  { name: 'GetVertexPositionInputs', kind: 'function', category: 'urp', returnType: 'VertexPositionInputs', parameters: [{ type: 'float3', name: 'positionOS' }], documentation: 'Computes URP vertex position values (object, world, view, clip, NDC).' },
  { name: 'GetVertexNormalInputs', kind: 'function', category: 'urp', returnType: 'VertexNormalInputs', parameters: [{ type: 'float3', name: 'normalOS' }], documentation: 'Computes URP vertex normal/tangent/bitangent in world space.' },
  // === URP lighting helpers ===
  { name: 'GetMainLight', kind: 'function', category: 'urp', returnType: 'Light', parameters: [], documentation: 'Returns the main directional light data for the current fragment.' },
  { name: 'GetAdditionalLight', kind: 'function', category: 'urp', returnType: 'Light', parameters: [{ type: 'uint', name: 'lightIndex' }, { type: 'float3', name: 'positionWS' }], documentation: 'Returns the additional light data at the given index for a world-space position.' },
  // === Unity instancing and stereo helpers ===
  { name: 'UNITY_SETUP_INSTANCE_ID', kind: 'macro', category: 'urp', detail: 'Unity instancing macro', documentation: 'Sets up the per-instance ID for the current vertex/fragment.' },
  { name: 'UNITY_TRANSFER_INSTANCE_ID', kind: 'macro', category: 'urp', detail: 'Unity instancing macro', documentation: 'Forwards the instance ID from vertex to fragment input.' },
  { name: 'UNITY_VERTEX_INPUT_INSTANCE_ID', kind: 'macro', category: 'urp', detail: 'Unity instancing macro', documentation: 'Declares the instance ID input field on a vertex input struct.' },
  { name: 'UNITY_VERTEX_OUTPUT_STEREO', kind: 'macro', category: 'urp', detail: 'Unity stereo macro', documentation: 'Declares the stereo eye index output field on a vertex output struct.' },
  // === HDRP helpers (HDRP-specific; SRP Core shared helpers live under URP) ===
  { name: 'GetShadowFade', kind: 'function', category: 'hdrp', returnType: 'float', parameters: [{ type: 'float3', name: 'positionWS' }, { type: 'float3', name: 'cameraDirection' }], documentation: 'Returns the shadow fade factor for a position relative to the camera.' },
  { name: 'MainLightRealtimeShadow', kind: 'function', category: 'hdrp', returnType: 'float', parameters: [{ type: 'float4', name: 'shadowCoord' }], documentation: 'Samples the realtime shadow attenuation for the main light.' },
  { name: 'EvaluateBSDF', kind: 'function', category: 'hdrp', returnType: 'float3', parameters: [{ type: 'BSDFData', name: 'bsdfData' }, { type: 'float3', name: 'L' }, { type: 'float3', name: 'V' }], documentation: 'Evaluates an HDRP BSDF for a given light and view direction.' },
  { name: 'GetCurrentExposureMultiplier', kind: 'function', category: 'hdrp', returnType: 'float', parameters: [], documentation: 'Returns the current camera exposure multiplier used by HDRP shaders.' },
  { name: 'ApplyDecalToBaseColor', kind: 'function', category: 'hdrp', returnType: 'void', parameters: [{ type: 'DecalSurfaceData', name: 'decalSurfaceData' }, { type: 'inout float3', name: 'baseColor' }], documentation: 'Composites an HDRP decal sample onto a base color value.' },
  {
    name: 'CBUFFER_START',
    kind: 'macro',
    category: 'unitycg',
    detail: 'Unity constant buffer macro',
    documentation: 'Begins a Unity shader constant buffer.',
  },
  {
    name: 'CBUFFER_END',
    kind: 'macro',
    category: 'unitycg',
    detail: 'Unity constant buffer macro',
    documentation: 'Ends a Unity shader constant buffer.',
  },
  // === UnityCG legacy sampling macros and helpers ===
  { name: 'tex2Dlod', kind: 'function', category: 'unitycg', returnType: 'float4', parameters: [{ type: 'sampler2D', name: 'sampler' }, { type: 'float4', name: 'uv_lod' }], documentation: 'Samples a 2D texture with an explicit mip level.' },
  { name: 'tex2Dgrad', kind: 'function', category: 'unitycg', returnType: 'float4', parameters: [{ type: 'sampler2D', name: 'sampler' }, { type: 'float2', name: 'uv' }, { type: 'float2', name: 'ddx' }, { type: 'float2', name: 'ddy' }], documentation: 'Samples a 2D texture using explicit derivatives.' },
  { name: 'tex2Dbias', kind: 'function', category: 'unitycg', returnType: 'float4', parameters: [{ type: 'sampler2D', name: 'sampler' }, { type: 'float4', name: 'uv_bias' }], documentation: 'Samples a 2D texture with a mip bias.' },
  { name: 'texCUBE', kind: 'function', category: 'unitycg', returnType: 'float4', parameters: [{ type: 'samplerCUBE', name: 'sampler' }, { type: 'float3', name: 'dir' }], documentation: 'Samples a cube map using a direction vector.' },
  { name: 'texCUBElod', kind: 'function', category: 'unitycg', returnType: 'float4', parameters: [{ type: 'samplerCUBE', name: 'sampler' }, { type: 'float4', name: 'dir_lod' }], documentation: 'Samples a cube map with an explicit mip level.' },
  { name: 'UNITY_SAMPLE_TEX2D', kind: 'macro', category: 'unitycg', detail: 'UnityCG texture sampling macro', documentation: 'Samples a 2D texture using Unity’s legacy sampler abstraction.' },
  { name: 'UNITY_DECLARE_TEX2D', kind: 'macro', category: 'unitycg', detail: 'UnityCG texture declaration macro', documentation: 'Declares a 2D texture with paired sampler using Unity’s legacy abstraction.' },
  { name: 'UNITY_PASS_TEX2D', kind: 'macro', category: 'unitycg', detail: 'UnityCG texture forwarding macro', documentation: 'Forwards a Unity-declared 2D texture into another function.' },
  // === UnityCG built-in matrices and globals ===
  { name: 'UNITY_MATRIX_MVP', kind: 'macro', category: 'unitycg', detail: 'UnityCG matrix', documentation: 'Combined model-view-projection matrix.' },
  { name: 'UNITY_MATRIX_M', kind: 'macro', category: 'unitycg', detail: 'UnityCG matrix', documentation: 'Object-to-world (model) matrix.' },
  { name: 'UNITY_MATRIX_V', kind: 'macro', category: 'unitycg', detail: 'UnityCG matrix', documentation: 'World-to-camera (view) matrix.' },
  { name: 'UNITY_MATRIX_P', kind: 'macro', category: 'unitycg', detail: 'UnityCG matrix', documentation: 'Camera-to-clip (projection) matrix.' },
  { name: 'UNITY_MATRIX_VP', kind: 'macro', category: 'unitycg', detail: 'UnityCG matrix', documentation: 'Combined view-projection matrix.' },
  { name: 'unity_ObjectToWorld', kind: 'macro', category: 'unitycg', detail: 'UnityCG matrix', documentation: 'Object-to-world transformation matrix.' },
  { name: 'unity_WorldToObject', kind: 'macro', category: 'unitycg', detail: 'UnityCG matrix', documentation: 'World-to-object transformation matrix.' },
  { name: '_WorldSpaceCameraPos', kind: 'macro', category: 'unitycg', detail: 'UnityCG global', documentation: 'World-space position of the active camera.' },
  { name: '_Time', kind: 'macro', category: 'unitycg', detail: 'UnityCG global', documentation: 'Time in seconds since level load, packed as (t/20, t, t*2, t*3).' },
  { name: '_SinTime', kind: 'macro', category: 'unitycg', detail: 'UnityCG global', documentation: 'Sine of time, packed as (t/8, t/4, t/2, t).' },
  { name: '_CosTime', kind: 'macro', category: 'unitycg', detail: 'UnityCG global', documentation: 'Cosine of time, packed as (t/8, t/4, t/2, t).' },
  { name: 'POSITION', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'NORMAL', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TANGENT', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD0', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD1', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'COLOR', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'SV_POSITION', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_Target', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_VertexID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_InstanceID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'Blend', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Cull', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'ZWrite', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'ZTest', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Offset', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'ColorMask', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Tags', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'LOD', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Pass', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab block keyword' },
  { name: 'SubShader', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab block keyword' },
  { name: 'Off', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'On', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Back', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Front', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Always', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'LEqual', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Less', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Greater', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Equal', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  // === Additional ShaderLab states ===
  { name: 'Stencil', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'BlendOp', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Lighting', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Material', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Fog', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'AlphaToMask', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Conservative', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Name', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab Pass name declaration' },
  { name: 'UsePass', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab pass reuse directive' },
  { name: 'GrabPass', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab grab pass directive' },
  { name: 'Fallback', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab fallback shader directive' },
  { name: 'CustomEditor', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab custom inspector directive' },
  { name: 'Category', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab category block keyword' },
  // === Additional ShaderLab state values (blend factors, blend ops, ztest, stencil ops) ===
  { name: 'Zero', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'One', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'SrcColor', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'SrcAlpha', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'DstColor', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'DstAlpha', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'OneMinusSrcColor', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'OneMinusSrcAlpha', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'OneMinusDstColor', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'OneMinusDstAlpha', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Add', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Sub', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'RevSub', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Min', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Max', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Never', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'GEqual', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'NotEqual', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Replace', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Keep', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Invert', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'IncrSat', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'DecrSat', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'IncrWrap', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'DecrWrap', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  // === Additional shader semantics ===
  { name: 'TEXCOORD2', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD3', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD4', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD5', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD6', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD7', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'COLOR0', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'COLOR1', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'COLOR2', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'COLOR3', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'SV_Depth', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_DepthGreaterEqual', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_DepthLessEqual', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_RenderTargetArrayIndex', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_ViewportArrayIndex', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_PrimitiveID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_IsFrontFace', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_SampleIndex', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_GroupID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_GroupThreadID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_DispatchThreadID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_DomainLocation', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'BLENDINDICES', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'BLENDWEIGHT', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'PSIZE', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'VFACE', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
] satisfies readonly BuiltinEntry[];
