import type { BuiltinEntry } from './types';

const shaderLabStateDetail = 'ShaderLab render state';
const shaderLabValueDetail = 'ShaderLab state value';

export const BUILTIN_ENTRIES = [
  {
    name: 'float2',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Two-component 32-bit floating point vector.',
  },
  {
    name: 'float3',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Three-component 32-bit floating point vector.',
  },
  {
    name: 'float4',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Four-component 32-bit floating point vector.',
  },
  {
    name: 'half',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL scalar type',
    documentation: '16-bit floating point scalar used in shader code.',
  },
  {
    name: 'half2',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Two-component half precision vector.',
  },
  {
    name: 'half3',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Three-component half precision vector.',
  },
  {
    name: 'half4',
    kind: 'type',
    category: 'hlsl',
    detail: 'HLSL vector type',
    documentation: 'Four-component half precision vector.',
  },
  {
    name: 'normalize',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Returns x scaled to unit length.',
  },
  {
    name: 'dot',
    kind: 'function',
    category: 'hlsl',
    returnType: 'scalar',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the dot product of x and y.',
  },
  {
    name: 'cross',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the cross product of two 3D vectors.',
  },
  {
    name: 'lerp',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
      { type: 'T', name: 's' },
    ],
    documentation: 'Linearly interpolates between x and y by s.',
  },
  {
    name: 'saturate',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Clamps x to the 0 to 1 range.',
  },
  {
    name: 'mul',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Performs matrix and vector multiplication.',
  },
  {
    name: 'clamp',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'minValue' },
      { type: 'T', name: 'maxValue' },
    ],
    documentation: 'Clamps x to the supplied range.',
  },
  {
    name: 'min',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the lesser of x and y.',
  },
  {
    name: 'max',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns the greater of x and y.',
  },
  {
    name: 'pow',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [
      { type: 'T', name: 'x' },
      { type: 'T', name: 'y' },
    ],
    documentation: 'Returns x raised to the power y.',
  },
  {
    name: 'sin',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Returns the sine of x.',
  },
  {
    name: 'cos',
    kind: 'function',
    category: 'hlsl',
    returnType: 'T',
    parameters: [{ type: 'T', name: 'x' }],
    documentation: 'Returns the cosine of x.',
  },
  {
    name: 'tex2D',
    kind: 'function',
    category: 'hlsl',
    returnType: 'float4',
    parameters: [
      { type: 'sampler2D', name: 'sampler' },
      { type: 'float2', name: 'uv' },
    ],
    documentation: 'Samples a texture using a sampler and UV coordinate.',
  },
  {
    name: 'UnityObjectToClipPos',
    kind: 'function',
    category: 'unitycg',
    returnType: 'float4',
    parameters: [{ type: 'float3', name: 'pos' }],
    documentation: 'Transforms object-space position to homogeneous clip space.',
  },
  {
    name: 'TRANSFORM_TEX',
    kind: 'macro',
    category: 'unitycg',
    detail: 'UnityCG texture transform macro',
    documentation: 'Applies Unity texture scale and offset to a UV coordinate.',
  },
  {
    name: 'SAMPLE_TEXTURE2D',
    kind: 'macro',
    category: 'urp',
    detail: 'URP texture sampling macro',
    documentation: 'Samples a Texture2D with an explicit sampler and UV coordinate.',
  },
  {
    name: 'TEXTURE2D',
    kind: 'macro',
    category: 'urp',
    detail: 'URP texture declaration macro',
    documentation: 'Declares a Texture2D resource.',
  },
  {
    name: 'SAMPLER',
    kind: 'macro',
    category: 'urp',
    detail: 'URP sampler declaration macro',
    documentation: 'Declares a sampler state.',
  },
  {
    name: 'CBUFFER_START',
    kind: 'macro',
    category: 'unitycg',
    detail: 'Unity constant buffer macro',
    documentation: 'Begins a Unity shader constant buffer.',
  },
  {
    name: 'CBUFFER_END',
    kind: 'macro',
    category: 'unitycg',
    detail: 'Unity constant buffer macro',
    documentation: 'Ends a Unity shader constant buffer.',
  },
  { name: 'POSITION', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'NORMAL', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TANGENT', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD0', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'TEXCOORD1', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'COLOR', kind: 'semantic', category: 'semantic', detail: 'Shader semantic' },
  { name: 'SV_POSITION', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_Target', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_VertexID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'SV_InstanceID', kind: 'semantic', category: 'semantic', detail: 'System value semantic' },
  { name: 'Blend', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Cull', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'ZWrite', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'ZTest', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Offset', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'ColorMask', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Tags', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'LOD', kind: 'state', category: 'shaderlab', detail: shaderLabStateDetail },
  { name: 'Pass', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab block keyword' },
  { name: 'SubShader', kind: 'keyword', category: 'shaderlab', detail: 'ShaderLab block keyword' },
  { name: 'Off', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'On', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Back', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Front', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Always', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'LEqual', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Less', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Greater', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
  { name: 'Equal', kind: 'keyword', category: 'shaderlab', detail: shaderLabValueDetail },
] satisfies readonly BuiltinEntry[];
