import type {
  AdapterSourceRevision,
  CompileProfile,
} from './adapter';
import type {
  CompilerEvidenceStaleReason,
  CompilerEvidenceProvenance,
  CompilerMappedLocation,
  CompilerSourceIdentity,
  CompilerVirtualView,
} from './compiler';
import type {
  GpuCaptureCorrelationResult,
  GpuCaptureTraceVerification,
} from './gpuCapture';
import type {
  MaterialContextAsset,
  MaterialContextProgram,
  SelectedMaterialContext,
} from './materialContext';
import type { Range } from './symbols';
import type { ShaderProgramContextEntry } from './structure';
import type {
  VariantBuildContextEvidence,
  VariantBuildEvidenceProvenance,
  VariantBuildFailure,
  VariantBuildStatus,
} from './variants';

/** The only question supported by the first evidence-explanation slice. */
export const PASS_EXPLANATION_QUESTION =
  'why-pass-selected-for-current-material-context';
export const PASS_EXPLANATION_SCHEMA_VERSION = 1;

/**
 * Dedicated Adapter capability for an authoritative Pass-selection decision.
 * Material Context evidence may report an observation, but cannot stand in for
 * this independently versioned causal fact.
 */
export const PASS_SELECTION_DECISION_CAPABILITY =
  'pass-selection-decision/v1';
export const PASS_SELECTION_DECISION_SCHEMA_VERSION = 1;
export const PASS_SELECTION_RATIONALE_SCHEMA_VERSION = 1;

/** Read-only pull for the current URI's local, session-scoped explanation. */
export const PASS_EXPLANATION_REQUEST = 'unityShaderNav/passExplanation';

/** User command that presents the structured explanation for the active source. */
export const EXPLAIN_CURRENT_PASS_COMMAND =
  'unityShaderNav.explainCurrentPass';

/** Hard bounds applied before the engine traverses untrusted graph payloads. */
export const MAX_PASS_EXPLANATION_PAYLOAD_BYTES = 256 * 1_024;
export const MAX_PASS_EXPLANATION_ANSWER_BYTES = 512 * 1_024;
export const MAX_PASS_EXPLANATION_NODES = 64;
export const MAX_PASS_EXPLANATION_EDGES = 128;
export const MAX_PASS_EXPLANATION_ID_LENGTH = 128;
/** Shared bound for arrays nested inside one evidence node or answer citation. */
export const MAX_PASS_EXPLANATION_NESTED_ITEMS = 256;
export const MAX_PASS_EXPLANATION_DISCLOSURES = 2_048;

export interface PassExplanationParams {
  readonly textDocument: { readonly uri: string };
}

export interface PassExplanationSourceNode {
  readonly id: string;
  readonly kind: 'source-pass';
  readonly source: CompilerSourceIdentity;
  readonly program: ShaderProgramContextEntry;
  /** Exact source range occupied by the selected Pass. */
  readonly range: Range;
}

export interface PassExplanationMaterialNode {
  readonly id: string;
  readonly kind: 'material-context';
  /**
   * Minimal selection identity used by this question. Material properties,
   * textures, and keyword inventories are intentionally excluded because they
   * neither authorize nor explain Pass selection.
   */
  readonly context: PassExplanationMaterialContext;
}

export interface PassExplanationMaterialContext {
  readonly selectionId: string;
  readonly material: MaterialContextAsset;
  readonly shader: MaterialContextAsset;
  readonly selectedProgram?: MaterialContextProgram;
  readonly provenance: SelectedMaterialContext['provenance'];
}

/**
 * Exact final Shader Context evidence when available. Material Context alone
 * is intentionally not promoted to a draw Context.
 */
export interface PassExplanationContextNode {
  readonly id: string;
  readonly kind: 'shader-context';
  /**
   * The complete validated envelope is retained so draw/trace/mapping identity
   * cannot be detached from the projected Shader Context.
   */
  readonly correlation: PassExplanationCurrentGpuCaptureCorrelation;
}

export type PassExplanationCurrentGpuCaptureCorrelation = Extract<
  GpuCaptureCorrelationResult,
  { readonly status: 'current' }
> & {
  /**
   * Complete trace verification identity. The status string on the upstream
   * correlation result is not independently sufficient to authorize cause.
   */
  readonly traceVerification: GpuCaptureTraceVerification;
};

/** Parent build identity retained alongside one projected Variant Context. */
export interface PassExplanationVariantBuild {
  readonly status: VariantBuildStatus;
  readonly provenance: VariantBuildEvidenceProvenance;
  readonly failure?: VariantBuildFailure;
}

/** Existing aggregate Variant build evidence projected without losing status. */
export interface PassExplanationVariantNode {
  readonly id: string;
  readonly kind: 'variant';
  readonly build: PassExplanationVariantBuild;
  readonly context: VariantBuildContextEvidence;
}

interface PassExplanationCompilerRecordBase {
  /** SHA-256 identity generated by the compiler-evidence registry. */
  readonly evidenceId: string;
  readonly sourceUri: string;
  readonly contextId: string;
  readonly profile: CompileProfile;
  readonly views: readonly PassExplanationCompilerView[];
  readonly provenance: CompilerEvidenceProvenance;
}

export interface PassExplanationCompilerView extends CompilerVirtualView {
  /** SHA-256 of the exact rendered virtual-document snapshot. */
  readonly contentHash: string;
}

/**
 * A compiler record is explicit about whether its registry identity is still
 * current. A stale record remains auditable but cannot support a current join.
 */
export type PassExplanationCompilerRecord =
  | (PassExplanationCompilerRecordBase & {
      readonly status: 'current';
    })
  | (PassExplanationCompilerRecordBase & {
      readonly status: 'stale';
      readonly reason: CompilerEvidenceStaleReason;
    });

export interface PassExplanationCompilerNode {
  readonly id: string;
  readonly kind: 'compiler';
  readonly record: PassExplanationCompilerRecord;
}

export type PassExplanationGeneratedView =
  Omit<CompilerVirtualView, 'kind'> & { readonly kind: 'generated' };

export interface PassExplanationGeneratedDocumentIdentity {
  /** SHA-256 of the exact UTF-8 generated virtual-document snapshot. */
  readonly contentHash: string;
  /** Exact mapped generated-code range whose source mapping is cited. */
  readonly range: Range;
}

export interface PassExplanationGeneratedNode {
  readonly id: string;
  readonly kind: 'generated-source';
  /** Must join the owning compiler record, not merely resemble its URI. */
  readonly evidenceId: string;
  readonly view: PassExplanationGeneratedView;
  readonly document: PassExplanationGeneratedDocumentIdentity;
  /** Exact, provenance-bearing mapping; approximate locations are not accepted. */
  readonly mapping: PassExplanationGeneratedMapping;
}

export type PassExplanationGeneratedMapping =
  Omit<CompilerMappedLocation, 'provenance'> & {
    /**
     * Registry-owned generated side of the exact mapping pair. This is not the
     * preceding #line directive range.
     */
    readonly generatedRange: Range;
    readonly provenance:
    Omit<CompilerMappedLocation['provenance'], 'method' | 'directive'> & {
      readonly method: 'line-directive';
      /**
       * The directive establishes the source alias and starting line, while
       * generatedRange identifies the later generated line that actually
       * matched the source snapshot.
       */
      readonly directive: NonNullable<
        CompilerMappedLocation['provenance']['directive']
      >;
    };
  };

export type PassExplanationEvidenceNode =
  | PassExplanationSourceNode
  | PassExplanationMaterialNode
  | PassExplanationContextNode
  | PassExplanationVariantNode
  | PassExplanationCompilerNode
  | PassExplanationGeneratedNode;

export interface PassSelectionDecisionProvenance {
  readonly capability: typeof PASS_SELECTION_DECISION_CAPABILITY;
  readonly projectId: string;
  readonly instanceId: string;
  readonly adapterVersion: string;
  readonly unityVersion: string;
  /** Unix epoch milliseconds. */
  readonly collectedAt: number;
}

export interface PassSelectionRationaleFact {
  readonly name: string;
  readonly value: string;
}

/**
 * Adapter-authored explanation of the selection rule that actually fired.
 * Identity closure alone attests what was selected; this rationale is required
 * before the answer may claim why.
 */
export interface PassSelectionRationale {
  readonly schemaVersion: typeof PASS_SELECTION_RATIONALE_SCHEMA_VERSION;
  readonly ruleId: string;
  readonly summary: string;
  readonly facts: readonly PassSelectionRationaleFact[];
}

/**
 * Self-contained identity of one Adapter-authored selection decision. Every
 * join key remains present even when the surrounding graph is serialized.
 */
export interface PassSelectionDecisionEvidence {
  readonly schemaVersion: typeof PASS_SELECTION_DECISION_SCHEMA_VERSION;
  readonly decisionId: string;
  readonly selectionId: string;
  readonly program: MaterialContextProgram;
  readonly materialRevision: AdapterSourceRevision;
  readonly shaderRevision: AdapterSourceRevision;
  readonly contextId: string;
  readonly rationale: PassSelectionRationale;
  readonly provenance: PassSelectionDecisionProvenance;
}

export interface PassSelectionDecisionEdge {
  readonly id: string;
  readonly kind: 'selection-decision';
  readonly materialNodeId: string;
  readonly contextNodeId: string;
  readonly sourceNodeId: string;
  /**
   * This is an Adapter-authored decision fact, not a reason inferred from
   * nearby source, keyword names, generated text, or compiler success.
   */
  readonly reason: 'adapter-reported-material-pass-selection';
  readonly decision: PassSelectionDecisionEvidence;
}

export interface PassContextVariantEdge {
  readonly id: string;
  readonly kind: 'context-variant';
  readonly fromNodeId: string;
  readonly toNodeId: string;
}

export interface PassContextCompilerEdge {
  readonly id: string;
  readonly kind: 'context-compiler';
  readonly fromNodeId: string;
  readonly toNodeId: string;
}

export interface PassCompilerGeneratedEdge {
  readonly id: string;
  readonly kind: 'compiler-generated';
  readonly fromNodeId: string;
  readonly toNodeId: string;
}

export interface PassGeneratedSourceEdge {
  readonly id: string;
  readonly kind: 'generated-source-map';
  readonly fromNodeId: string;
  readonly toNodeId: string;
}

export type PassExplanationEvidenceEdge =
  | PassSelectionDecisionEdge
  | PassContextVariantEdge
  | PassContextCompilerEdge
  | PassCompilerGeneratedEdge
  | PassGeneratedSourceEdge;

/**
 * JSON-safe, session-scoped input. The engine never persists or transmits it.
 */
export interface PassExplanationEvidenceGraph {
  readonly schemaVersion: typeof PASS_EXPLANATION_SCHEMA_VERSION;
  readonly question: typeof PASS_EXPLANATION_QUESTION;
  readonly graphId: string;
  readonly nodes: readonly PassExplanationEvidenceNode[];
  readonly edges: readonly PassExplanationEvidenceEdge[];
}

export type PassExplanationEvidenceRequirement =
  | 'material-context'
  | 'selected-program'
  | 'source-pass'
  | 'shader-context'
  | 'selection-decision'
  | 'variant'
  | 'context-variant-link'
  | 'compiler'
  | 'context-compiler-link'
  | 'generated-source'
  | 'compiler-generated-link'
  | 'generated-source-map-link';

export interface PassExplanationMissingEvidence {
  readonly evidence: PassExplanationEvidenceRequirement;
  /** Optional corroboration is disclosed but does not manufacture a refusal. */
  readonly blocksCausalClaim: boolean;
  readonly detail: string;
}

/**
 * One list, so the server vocabulary and the client's accepted set cannot
 * drift. `internal-error` is the only code that does not describe the project's
 * evidence: it reports that this engine failed to evaluate an already
 * shape-valid graph.
 */
export const PASS_EXPLANATION_CONTRADICTION_CODES = [
  'invalid-graph',
  'internal-error',
  'payload-limit-exceeded',
  'node-limit-exceeded',
  'edge-limit-exceeded',
  'invalid-node',
  'invalid-edge',
  'duplicate-node-id',
  'duplicate-edge-id',
  'dangling-edge',
  'edge-kind-mismatch',
  'multiple-selection-decisions',
  'multiple-primary-evidence',
  'decision-provenance-mismatch',
  'selected-program-mismatch',
  'shader-identity-mismatch',
  'shader-context-mismatch',
  'source-revision-mismatch',
  'project-identity-mismatch',
  'instance-identity-mismatch',
  'adapter-session-mismatch',
  'variant-context-mismatch',
  'compiler-context-mismatch',
  'compiler-profile-mismatch',
  'generated-mapping-mismatch',
] as const;

export type PassExplanationContradictionCode =
  typeof PASS_EXPLANATION_CONTRADICTION_CODES[number];

export interface PassExplanationContradiction {
  readonly code: PassExplanationContradictionCode;
  readonly detail: string;
  readonly nodeIds: readonly string[];
  readonly edgeIds: readonly string[];
}

export interface PassExplanationSourceCitation {
  readonly nodeId: string;
  readonly kind: 'source-pass';
  readonly source: CompilerSourceIdentity;
  readonly program: ShaderProgramContextEntry;
  readonly range: Range;
}

export interface PassExplanationMaterialCitation {
  readonly nodeId: string;
  readonly kind: 'material-context';
  readonly selectionId: string;
  readonly material: MaterialContextAsset;
  readonly shader: MaterialContextAsset;
  readonly selectedProgram?: MaterialContextProgram;
  readonly provenance: SelectedMaterialContext['provenance'];
}

export interface PassExplanationContextCitation {
  readonly nodeId: string;
  readonly kind: 'shader-context';
  readonly correlation: PassExplanationCurrentGpuCaptureCorrelation;
}

export interface PassExplanationVariantCitation {
  readonly nodeId: string;
  readonly kind: 'variant';
  readonly build: PassExplanationVariantBuild;
  readonly context: VariantBuildContextEvidence;
}

export interface PassExplanationCompilerCitation {
  readonly nodeId: string;
  readonly kind: 'compiler';
  readonly record: PassExplanationCompilerRecord;
}

export interface PassExplanationGeneratedCitation {
  readonly nodeId: string;
  readonly kind: 'generated-source';
  readonly evidenceId: string;
  readonly view: PassExplanationGeneratedView;
  readonly document: PassExplanationGeneratedDocumentIdentity;
  readonly mapping: PassExplanationGeneratedMapping;
}

export type PassExplanationCitation =
  | PassExplanationSourceCitation
  | PassExplanationMaterialCitation
  | PassExplanationContextCitation
  | PassExplanationVariantCitation
  | PassExplanationCompilerCitation
  | PassExplanationGeneratedCitation;

export type PassSelectionObservation =
  | {
      readonly status: 'observed';
      readonly statement: string;
      readonly materialName: string;
      readonly shaderName: string;
      readonly selectedProgram: MaterialContextProgram;
      readonly citationNodeIds: readonly string[];
    }
  | {
      readonly status: 'not-observed';
      readonly reason:
        | 'material-context-missing'
        | 'material-context-ambiguous'
        | 'selected-program-unavailable';
      readonly statement: string;
      readonly citationNodeIds: readonly string[];
    };

export type PassCausalExplanation =
  | {
      readonly status: 'supported';
      readonly reason: 'authoritative-selection-decision';
      readonly statement: string;
      /** Complete, audit-ready decision fact; never an opaque edge id alone. */
      readonly decision: PassSelectionDecisionEdge;
      readonly citationNodeIds: readonly string[];
    }
  | {
      readonly status: 'refused';
      readonly reason:
        | 'insufficient-evidence'
        | 'contradictory-evidence'
        | 'invalid-evidence';
      readonly statement: string;
      readonly citationNodeIds: readonly string[];
    };

export interface PassExplanationAnswer {
  readonly schemaVersion: typeof PASS_EXPLANATION_SCHEMA_VERSION;
  readonly question: typeof PASS_EXPLANATION_QUESTION;
  readonly graphId: string;
  readonly observation: PassSelectionObservation;
  readonly causalExplanation: PassCausalExplanation;
  readonly disclosures: {
    readonly missing: readonly PassExplanationMissingEvidence[];
    readonly contradictions: readonly PassExplanationContradiction[];
  };
  readonly citations: readonly PassExplanationCitation[];
  /** v1 has no edit protocol or apply authority. */
  readonly suggestedEdits: readonly [];
  readonly execution: {
    readonly authority: 'deterministic-local-evidence-engine';
    readonly locality: 'local-only';
    readonly model: 'not-used';
    readonly telemetry: 'none';
    readonly retention: 'session-only';
  };
}
